#!/bin/bash

IPADDR=`hostname -I`	 #change to "hostname -I" on raspberry pi, on mac: "ipconfig getifaddr en1" \

#to remove last bit of ip address \
firstNum=`echo $IPADDR | cut -c 1`
endIP=${IPADDR##$firstNum*.}
rmIP=${IPADDR%$endIP}

num=1
until [ $num -gt 255 ]
do
  modIP="$rmIP$num"
  if ping -c 1 -W 1 "$modIP" >/dev/null 2>&1; then
    echo $modIP : alive
    host=`host $modIP | cut -d' ' -f5`
    echo "host : $host"
    MAC=`grep $modIP /proc/net/arp | cut -d' ' -f4` 
    echo "MAC : $MAC"
    echo `nc -zv $modIP 20`
    echo `nc -zv $modIP 22`
    echo `nc -vz $modIP 25`
    echo `nc -zv $modIP 80`
    echo " "
  fi
  ((num++))
done
