#!/bin/bash

IPADDR=`hostname -I`	 #change to "hostname -I" on raspberry pi, on mac: "ipconfig getifaddr en1" \

#to remove last bit of ip address \
firstNum=`echo $IPADDR | cut -c 1`
endIP=${IPADDR##$firstNum*.}
rmIP=${IPADDR%$endIP}

num=1
until [ $num -gt 255 ]
do
  modIP="$rmIP$num"
  if ping -c 1 -W 1 "$modIP" >/dev/null 2>&1; then
    echo $modIP : alive
    host=`host $modIP | cut -d' ' -f5`
    echo "host : $host"
    arpFile=`grep $modIP /proc/net/arp`
    MAC=`echo $arpFile | cut -d' ' -f4`
    echo MAC : $MAC
    for port in 20 22 25 80
    do
      if `nc -z $modIP $port` >/dev/null 2>&1; then
        echo "Port $port : Successful!"
      else
        echo "Port $port : Not available"
      fi
    done
    echo " "
  fi
((num++))
done
